## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Abdulwasiu Bamidele Popoola
#### Email: waga43tech@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

In [9]:
# To show all outputs in the cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [149]:
import torch
import random
torch.__version__


'2.5.1'

In [2]:
# Exercise 1a- Solution
a = torch.tensor([1, 2])


### Additional Exercises Solution

In [3]:
print(type(a))


<class 'torch.Tensor'>


### Q1: Documentation Reading

<mark>Done</mark>

####

### Q2: Create a random tensor with shape (7, 7).

In [159]:
random_tensor_1 = torch.rand(size=(7, 7))
random_tensor_1
print(f"The shape of random_tensor_1 variable is: {random_tensor_1.shape}")


tensor([[0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742],
        [0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037]])

The shape of random_tensor_1 variable is: torch.Size([7, 7])


### Q3: Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [160]:
random_tensor_2 = torch.rand(1,7)
random_tensor_2
print(f"The shape of random_tensor_2 variable is: {random_tensor_2.shape}")


tensor([[0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883]])

The shape of random_tensor_2 variable is: torch.Size([1, 7])


In [143]:
# def matrix_mult(matrix_1=torch.rand(size=(7, 7)), matrix_2=torch.rand(1,7)):
#     print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
#           f"\n{random_tensor_1}\n"
#           f"\nThe shape of Tensor 2:\t{random_tensor_2.shape}.\n"
#           f"{random_tensor_2}\n")

#     try:
#         torch.matmul(random_tensor_1, random_tensor_2)
#     except RuntimeError:
#         print(f"Matrix multiplication not possible due to shape mismatch:\nTensor 1:\t{random_tensor_1.shape} multiplied by\nTensor 2:\t{random_tensor_2.shape}.\n")
#         print(f"{'Reshaping':=^70}")
#         print(f"Solving by reshaping random_tensor_2 from {random_tensor_2.shape} to [7, 1].")
#         random_tensor_2_reshaped = random_tensor_2.reshape(7,1)
#         print(f"Matrix multiplication now possible due to shape match:\nTensor 1:\t\t{random_tensor_1.shape} multiplied by\nTensor 2 reshaped:\t{random_tensor_2_reshaped.shape}.\n")
#         print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
#           f"\n{random_tensor_1}\n"
#           f"\nThe shape of Tensor 2 reshaped:\t{random_tensor_2.shape}.\n"
#           f"{random_tensor_2_reshaped}\n")
#         print(f"{'Printing out the matrix multiplication ⤵️':=^70}")
#         torch.matmul(random_tensor_1, random_tensor_2_reshaped)

# matrix_mult()


In [161]:
print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
          f"\n{random_tensor_1}\n"
          f"\nThe shape of Tensor 2:\t{random_tensor_2.shape}.\n"
          f"{random_tensor_2}\n")

try:
    torch.matmul(random_tensor_1, random_tensor_2)
except RuntimeError:
    print(f"Matrix multiplication not possible due to shape mismatch:\nTensor 1:\t{random_tensor_1.shape} multiplied by\nTensor 2:\t{random_tensor_2.shape}.\n")
    print(f"{'Reshaping':=^70}")
    print(f"Solving by reshaping random_tensor_2 from {random_tensor_2.shape} to [7, 1].")
    random_tensor_2_reshaped = random_tensor_2.reshape(7,1)
    print(f"\nMatrix multiplication now possible due to shape match:\nTensor 1:\t\t{random_tensor_1.shape} multiplied by\nTensor 2 reshaped:\t{random_tensor_2_reshaped.shape}.\n")
    print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
        f"\n{random_tensor_1}\n"
        f"\nThe shape of Tensor 2 reshaped:\t{random_tensor_2.shape}.\n"
        f"{random_tensor_2_reshaped}\n")
    print(f"{'Printing out the matrix multiplication ⤵️':=^70}")
    torch.matmul(random_tensor_1, random_tensor_2_reshaped)


The shape of the Tensor 1:	torch.Size([7, 7]).

tensor([[0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742],
        [0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037]])

The shape of Tensor 2:	torch.Size([1, 7]).
tensor([[0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883]])

Matrix multiplication not possible due to shape mismatch:
Tensor 1:	torch.Size([7, 7]) multiplied by
Tensor 2:	torch.Size([1, 7]).

==============================Reshaping===============================
Solving by reshaping random_tensor_2 from torch.Size([1, 7]) to [7, 1].

Matrix multiplication now possible due to shape match:
Tensor 1:		torch.Size([7, 7]) multiplied by
Te

tensor([[0.9454],
        [0.9473],
        [0.7089],
        [1.4405],
        [1.3714],
        [0.9152],
        [0.9704]])

### Q3: Set the random seed to 0 and do exercises 2 & 3 over again.

In [184]:
print(f"\n{'Setting random seed using Torch':=^70}\n")

random_seed = 0
torch.manual_seed(seed=random_seed)
random_tensor_1 = torch.rand(7,7)
random_tensor_2 = torch.rand(1,7)
random_tensor_2_reshaped = torch.reshape(random_tensor_2,(7,1))

print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
          f"\n{random_tensor_1}\n"
          f"\nThe shape of Tensor 2:\t{random_tensor_2.shape}.\n"
          f"{random_tensor_2}\n")

try:
    torch.matmul(random_tensor_1, random_tensor_2)
except RuntimeError:
    print(f"Matrix multiplication not possible due to shape mismatch:\nTensor 1:\t{random_tensor_1.shape} multiplied by\nTensor 2:\t{random_tensor_2.shape}.\n")
    print(f"{'Reshaping':=^70}")
    print(f"Solving by reshaping random_tensor_2 from {random_tensor_2.shape} to [7, 1].")
    random_tensor_2_reshaped = random_tensor_2.reshape(7,1)
    print(f"\nMatrix multiplication now possible due to shape match:\nTensor 1:\t\t{random_tensor_1.shape} multiplied by\nTensor 2 reshaped:\t{random_tensor_2_reshaped.shape}.\n")
    print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
        f"\n{random_tensor_1}\n"
        f"\nThe shape of Tensor 2 reshaped:\t{random_tensor_2.shape}.\n"
        f"{random_tensor_2_reshaped}\n")
    print(f"{'Printing out the matrix multiplication ⤵️':=^70}")
    torch.matmul(random_tensor_1, random_tensor_2_reshaped)




===================Setting random seed using Torch====================



The shape of the Tensor 1:	torch.Size([7, 7]).

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

The shape of Tensor 2:	torch.Size([1, 7]).
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

Matrix multiplication not possible due to shape mismatch:
Tensor 1:	torch.Size([7, 7]) multiplied by
Tensor 2:	torch.Size([1, 7]).

==============================Reshaping===============================
Solving by reshaping random_tensor_2 from torch.Size([1, 7]) to [7, 1].

Matrix multiplication now possible due to shape match:
Tensor 1:		torch.Size([7, 7]) multiplied by
Te

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### Q4: Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [196]:
#help(torch.cuda)
# Check to see if my PC supports/has GPU
if torch.cuda.is_available == True:
    print("GPU is available for usage")
else:
    print("GPU is unavailable for use on this PC")

# random_tensor_1.device
#torch.cuda.is_available()
# torch.cuda.device_count()
# device = 'CPU is available for use' if torch.cuda.is_available() == False else 'GPU is available for use'
# device


GPU is unavailable for use on this PC


According to the documentation:

> It's safe to call this function if CUDA is not available; in that case, it is silently ignored.
>
> manual_seed(seed: int) -> None
> 
> Set the seed for generating random numbers for the current GPU.
>
> **.. warning::**
    If you are working with a multi-GPU model, this function is insufficient to get determinism.
>
> To seed all GPUs, use :func:`manual_seed_all`.

In [186]:
print(f"\n{'Setting random seed using GPU':=^70}\n")
random_seed = 1234
torch.cuda.manual_seed(seed=random_seed)
random_tensor_1 = torch.rand(7,7)
random_tensor_2 = torch.rand(1,7)
random_tensor_2_reshaped = torch.reshape(random_tensor_2,(7,1))

print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
          f"\n{random_tensor_1}\n"
          f"\nThe shape of Tensor 2:\t{random_tensor_2.shape}.\n"
          f"{random_tensor_2}\n")

try:
    torch.matmul(random_tensor_1, random_tensor_2)
except RuntimeError:
    print(f"Matrix multiplication not possible due to shape mismatch:\nTensor 1:\t{random_tensor_1.shape} multiplied by\nTensor 2:\t{random_tensor_2.shape}.\n")
    print(f"{'Reshaping':=^70}")
    print(f"Solving by reshaping random_tensor_2 from {random_tensor_2.shape} to [7, 1].")
    random_tensor_2_reshaped = random_tensor_2.reshape(7,1)
    print(f"\nMatrix multiplication now possible due to shape match:\nTensor 1:\t\t{random_tensor_1.shape} multiplied by\nTensor 2 reshaped:\t{random_tensor_2_reshaped.shape}.\n")
    print(f"The shape of the Tensor 1:\t{random_tensor_1.shape}.\n"
        f"\n{random_tensor_1}\n"
        f"\nThe shape of Tensor 2 reshaped:\t{random_tensor_2.shape}.\n"
        f"{random_tensor_2_reshaped}\n")
    print(f"{'Printing out the matrix multiplication ⤵️':=^70}")
    torch.matmul(random_tensor_1, random_tensor_2_reshaped)




====================Setting random seed using GPU=====================

The shape of the Tensor 1:	torch.Size([7, 7]).

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

The shape of Tensor 2:	torch.Size([1, 7]).
tensor([[0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]])

Matrix multiplication not possible due to shape mismatch:
Tensor 1:	torch.Size([7, 7]) multiplied by
Tensor 2:	torch.Size([1, 7]).

==============================Reshaping===============================
Solving by reshaping random_tensor_2 from torch.Size([1, 7]) to [7, 1].

Matrix multiplication now po

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

### Q6: Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [276]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

torch.manual_seed(1234)
random_tensor_3 = torch.rand(2,3)
random_tensor_4 = torch.rand(2,3)

device_random_tensor_3 = random_tensor_3.to(device)
device_random_tensor_4 = random_tensor_4.to(device)

print(f"{device_random_tensor_3}\nDevice Type:\t{device_random_tensor_3.device}\n")
print(f"{device_random_tensor_4}\nDevice Type:\t{device_random_tensor_4.device}")


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Device Type:	cpu

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
Device Type:	cpu


### Q7: Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [270]:
print(f"\n{'Using random seed of 1234':=^70}\n")

device_random_tensor_4_reshaped = torch.reshape(device_random_tensor_4,(3, 2))

print(f"The shape of the Tensor 3:\t{device_random_tensor_3.shape}.\n"
          f"\n{device_random_tensor_3}\n"
          f"\nThe shape of Tensor 4:\t{device_random_tensor_4.shape}.\n"
          f"{device_random_tensor_4}\n")

try:
    torch.mm(device_random_tensor_3, device_random_tensor_4)
except RuntimeError:
    print(f"Matrix multiplication not possible due to shape mismatch:\nTensor 3:\t{device_random_tensor_3.shape} multiplied by\nTensor 4:\t{device_random_tensor_4.shape}.\n")
    print(f"{'Reshaping':=^70}")
    print(f"Solving by reshaping device_random_tensor_4 from {device_random_tensor_4.shape} to [3, 2].")
    device_random_tensor_4_reshaped = device_random_tensor_4.reshape(3, 2)
    print(f"\nMatrix multiplication now possible due to shape match:\nTensor 3:\t\t{device_random_tensor_3.shape} multiplied by\nTensor 4 reshaped:\t{device_random_tensor_4_reshaped.shape}.\n")
    print(f"The shape of the Tensor 3:\t{device_random_tensor_3.shape}.\n"
        f"\n{device_random_tensor_3}\n"
        f"\nThe shape of Tensor 4 reshaped:\t{device_random_tensor_4_reshaped.shape}.\n"
        f"{device_random_tensor_4_reshaped}\n")
    print(f"{'Printing out the matrix multiplication ⤵️':=^70}")
    output = torch.matmul(device_random_tensor_3, device_random_tensor_4_reshaped)
    output



======================Using random seed of 1234=======================

The shape of the Tensor 3:	torch.Size([2, 3]).

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

The shape of Tensor 4:	torch.Size([2, 3]).
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])

Matrix multiplication not possible due to shape mismatch:
Tensor 3:	torch.Size([2, 3]) multiplied by
Tensor 4:	torch.Size([2, 3]).

==============================Reshaping===============================
Solving by reshaping device_random_tensor_4 from torch.Size([2, 3]) to [3, 2].

Matrix multiplication now possible due to shape match:
Tensor 3:		torch.Size([2, 3]) multiplied by
Tensor 4 reshaped:	torch.Size([3, 2]).

The shape of the Tensor 3:	torch.Size([2, 3]).

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

The shape of Tensor 4 reshaped:	torch.Size([3, 2]).
tensor([[0.0518, 0.4681],
        [0.6738, 0.3315],
        [0.7837, 0.5631]])

==============Printing o

tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]])

### Q8: Find the maximum and minimum values of the output of 7.

In [222]:
output


tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]])

In [225]:
print(f"Minimum:\t{output.min()}\n"
      f"Maximum:\t{output.max()}")


Minimum:	0.2930890917778015
Maximum:	0.6073753833770752


### Q9: Find the maximum and minimum index values of the output of 7.

In [230]:
print(f"Index of the maximum value:\t{output.argmax()}\n"
      f"Index of the minimum value:\t{output.argmin()}")


Index of the maximum value:	2
Index of the minimum value:	1


### Q10: Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [267]:
torch.manual_seed(443)
tensor_1 = torch.rand(1, 1, 1, 10)
tensor_2 = tensor_1.squeeze()

print(f"{'Tensor 1:':=^70}\n{tensor_1}\nTensor 1 shape:\t{tensor_1.shape}\n\n\n"
      f"{'Tensor 2:':=^70}\n{tensor_2}\nTensor 2 Shape:\t{tensor_2.shape}")



==============================Tensor 1:===============================
tensor([[[[0.4726, 0.9538, 0.2345, 0.8960, 0.0762, 0.4543, 0.0288, 0.2434,
           0.8717, 0.3625]]]])
Tensor 1 shape:	torch.Size([1, 1, 1, 10])


==============================Tensor 2:===============================
tensor([0.4726, 0.9538, 0.2345, 0.8960, 0.0762, 0.4543, 0.0288, 0.2434, 0.8717,
        0.3625])
Tensor 2 Shape:	torch.Size([10])
